### ISSUE TITLE
write to txt file parametrizalasa

### ISSUE THREAD

**Issue by k15kristof** [k15kristof/polo_robot#4]
functions.append_to_smooth_data(ido, simitott_adat, derivalt)

megfixalas, ugy hogy tettszoleges bemeno parameter lehessen a fuggvenynek
segitseg:

[](https://stackoverflow.com/questions/847936/how-can-i-find-the-number-of-arguments-of-a-python-function)
[](https://stackoverflow.com/questions/919680/can-a-variable-number-of-arguments-be-passed-to-a-function)

**Comment by kmarci9** [comment]
csak annyi oszlop legyen a txt fajlba , amennyi argumentumot megkap

**Comment by k15kristof** [comment]
Ugy aa legegyszerűbb valszeg, hogyha egy listát kap meg a füvggvény (amibe listák vannak)

**Comment by k15kristof** [comment]
Készen, van használjátok EZT a függvényt ha akérmi ilyesmi kell!!!!!!!!!!!
