### ISSUE TITLE
convertCiklusidoToStep nem jó

### ISSUE THREAD

**Issue by hoacin293** [k15kristof/polo_robot#5]
Urzn nézd meg a megjegyzesemet a derivate/convertCiklusidoToStep-ben

**Comment by k15kristof** [comment]
Igazad, van, de még egyszerubb a helyzet, mint gondolnank ugyanis: ket mintavételezési pont közti távolságot akarjuk oraban kifejezni. Ugyanis: ciklusido = elemzesi_intervall / (derivalt_pontok-1)
Tehát, step = ciklusido/3600   - órában kifejezve a két mintavételezés közt eltelt idő.
szólj ha vhol rosszul gondolom

**Comment by hoacin293** [comment]
step = elemzesi_intervall / (derivalt_pontok * 3600)

így a jó :)
